# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=20)),
                ('att1', models.CharField(max_length=20)),
                ('att2', models.CharField(max_length=20)),
                ('att3', models.CharField(max_length=20)),
            ],
        ),
    ]
