# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(default='node_name', max_length=20)),
                ('att1', models.CharField(max_length=20)),
                ('att2', models.CharField(max_length=20)),
                ('att3', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(max_length=10)),
                ('rel_title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('rel_end', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='KBMS.Node')),
                ('rel_start', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='KBMS.Node')),
            ],
        ),
    ]
