# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KBMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rel',
            name='rel_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='KBMS.Node'),
        ),
        migrations.AlterField(
            model_name='rel',
            name='rel_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='KBMS.Node'),
        ),
    ]
