# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KBMS', '0002_auto_20170816_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_name',
            new_name='name',
        ),
    ]
