# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KBMS', '0004_ontology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='album_logo',
            new_name='ontology_logo',
        ),
    ]
